from collections import deque
HIHIHIHIHIHIHIHIHIHIHIHI = input()
KKKKKKKKKKKKKKKKKKKKKKKK = len(HIHIHIHIHIHIHIHIHIHIHIHI)
HIHIHIHIHIHIHIHIHIHIHIHI = int(HIHIHIHIHIHIHIHIHIHIHIHI)
AAAAAAAAAAAAAAAAAAAAAAAA = deque()
BBBBBBBBBBBBBBBBBBBBBBBB = deque()

for CCCCCCCCCCCCCCCCCCCCCCCC in range(0,KKKKKKKKKKKKKKKKKKKKKKKK):
    if CCCCCCCCCCCCCCCCCCCCCCCC<(KKKKKKKKKKKKKKKKKKKKKKKK/2):
        AAAAAAAAAAAAAAAAAAAAAAAA.append(HIHIHIHIHIHIHIHIHIHIHIHI//(10**(KKKKKKKKKKKKKKKKKKKKKKKK-CCCCCCCCCCCCCCCCCCCCCCCC-1)))
        HIHIHIHIHIHIHIHIHIHIHIHI%=(10**(KKKKKKKKKKKKKKKKKKKKKKKK-CCCCCCCCCCCCCCCCCCCCCCCC-1))
    else:
        BBBBBBBBBBBBBBBBBBBBBBBB.append(HIHIHIHIHIHIHIHIHIHIHIHI//(10**(KKKKKKKKKKKKKKKKKKKKKKKK-CCCCCCCCCCCCCCCCCCCCCCCC-1)))
        HIHIHIHIHIHIHIHIHIHIHIHI%=(10**(KKKKKKKKKKKKKKKKKKKKKKKK-CCCCCCCCCCCCCCCCCCCCCCCC-1))

TTTTTTTTTTTTTTTTTTTTTTTT=0
RRRRRRRRRRRRRRRRRRRRRRRR=0
while AAAAAAAAAAAAAAAAAAAAAAAA:
    TTTTTTTTTTTTTTTTTTTTTTTT+=AAAAAAAAAAAAAAAAAAAAAAAA.popleft()
    RRRRRRRRRRRRRRRRRRRRRRRR+=BBBBBBBBBBBBBBBBBBBBBBBB.popleft()

if TTTTTTTTTTTTTTTTTTTTTTTT==RRRRRRRRRRRRRRRRRRRRRRRR:
    print("LUCKY")
else:
    print("READY")